left:
  camera_index: 2
  crop: [199, 38, 385, 363]
  flip: true
  frame_height: 480
  frame_width: 640
  use_recommended_resolution: false
right:
  camera_index: 0
  crop: [131, 63, 465, 313]
  flip: true
  frame_height: 480
  frame_width: 640
  use_recommended_resolution: true
